# Generated by Django 4.2.1 on 2023-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncurtadorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000, verbose_name='link')),
                ('uid', models.CharField(max_length=5, verbose_name='id')),
            ],
        ),
    ]
